# -*- coding: utf-8 -*-
"""Práctica Clase 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CacVGHTKOGuPmPOXPyCIny2bCZ2lexw_
"""

'''
Ejercicio 1: 
Crear un programa que muestre por pantalla la cadena de texto "¡Hola Mundo!
'''

print("¡Hola Mundo!")

'''
Ejercicio 2: 
Crear un programa que almacene en una variable la cadena de texto "¡Hola Mundo!" 
y luego la muestre por pantalla.
'''

cadena_de_texto = "¡Hola Mundo!"
print(cadena_de_texto)

'''
Ejercicio 3:
Crear un programa que pida al usuario su nombre y su edad y luego muestre por 
pantalla los siguientes mensajes en renglones distintos:
Hola {nombre}
Tu edad es {edad} años
'''

nombre = input("Ingrese su nombre: ")
apellido = input("Ingrese su apellido: ")
edad = int(input("Ingrese su edad: "))
print()
print()
print(f"Hola {nombre}")
print(f"Tu edad es {edad} años :D")

'''
Ejercicio 4:
Crear un programa que pida al usuario su nombre y muestre por pantalla 
cuántas letras tiene.
'''

nombre = input("Ingrese su nombre: ")
print()
print(nombre + " tiene " + str(len(nombre)) + " letras")

'''
Ejercicio 5:
Crear un programa que realice la siguiente operación aritmética 
(3*8/2)2 y muestre por pantalla el resultado.
'''

print((3*8/2)**2)

'''
Ejercicio 6:
Crear un programa que lea un entero positivo, n, introducido por el usuario 
y después muestre en pantalla la suma de todos los enteros desde 1 hasta n.
'''

num = int(input("Introduzca un número: "))
suma = 0 #se le asigna valor 0 a la variable para que no afecte el cálculo

for i in range(1, num +1): #se va a comenzar la suma desde 1 hasta "num" (el numero introducido x el user) y se le va a sumar 1
  suma += i #i es el identificador que se le da a la variable q se crea en el FOR

print(suma)

'''
Ejercicio 7:
Crear un programa que pida al usuario el monto a invertir y calcular cuánto 
dinero tendrá en su cuenta al cabo de 6 meses si el interés mensual es 
de 5%. Mostrar el resultado por pantalla.
'''

monto = float(input("Introduzca el monto a invertir: $"))
interes = 0.05 # el 5% se pasa a decimal para poder hacer la cuenta
meses = 6
print("Su monto final será de: $" + str(round((monto * interes * meses) + monto)))

'''
Ejercicio 8:
Crear un programa que pida al usuario su edad y muestre por pantalla
si es mayor de edad o no
'''

edad = int(input("Ingrese su edad: "))
print()
if edad < 18:
  print("Sos menor de edad.")
else:
  print("Sos mayor de edad.")

'''
Ejercicio 9:
Crear un programa que almacene la cadena de caracteres contraseña en 
una variable, pregunte al usuario por la contraseña e imprima por pantalla 
si la contraseña introducida por el usuario coincide con la guardada en 
la variable sin tener en cuenta mayúsculas y minúsculas.
'''

contraseña = "Contraseña1234"
contraseña1 = str(input("Ingrese una contraseña: "))
if contraseña == contraseña1:
  print("La contraseña coincide")
else:
  print("La contraseña no coincide")

'''
Ejercicio 10:
Crear un programa que pida al usuario dos números y muestre por pantalla 
el cociente de la división entre ellos siempre que el segundo
número sea distinto de 0.
'''

numero_1 = int(input("Ingrese su primer número: "))
numero_2 = int(input("Ingrese su segundo número mayor que cero: "))
print()
print(numero_1 / numero_2)
print(round(numero_1 / numero_2))

'''
Ejercicio 11:
Crear un programa que pida al usuario un número entero y 
muestre por pantalla si es par o impar.
'''

numero = int(input("Ingrese un número entero: "))

if numero %2 == 0:
  print("Tu número es par")
else:
  print("Su número es impar")

'''
Ejercicio 12:
Crear un programa que pida al usuario una palabra y
la muestre por pantalla 10 veces.
'''

palabra = input("Ingrese una palabra: ")

print((palabra + " ") * 10)

'''
Ejercicio 13:
Crear una lista con 6 elementos, luego recorrerla e 
imprimir elemento a elemento en renglones distintos.
'''

lista = [123, "pancho", "hamburguesa", False, (34), (1, 5)]
for i in lista:
  print(i)

'''
Ejercicio 14:
Crear un programa que recorra un diccionario previamente creado y 
muestre por pantalla:
> clave → valor
'''

diccionario_gatos = {
        "Nombre": "Sköll",
        "Raza": "No tiene",
        "Edad": "7",
        "Pelaje": "Corto",
        "Color": "Blanco y negro" 
        }

for key, value in diccionario_gatos.items():
  print(f"{key} ---> {value}")

'''
Ejercicio 15:
Crear un programa que imprima por pantalla todo lo que el usuario ingresa 
hasta que ingresa la palabra “salir”.
'''

while True: # Quiere decir "Mientras sea verdad algo" es un loop infinito por ende necesita cortarse con un BREAK
  palabras = input("Ingrese una palabra: ")
  print(palabras)
  if palabras == "salir":
    break