# -*- coding: utf-8 -*-
"""Práctica Clase 5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18USFwiyFLtwzCT61VU-mlSk14fP8Dd8R
"""

'''
Ejercicio 1:
Crear un programa que muestre por pantalla la cadena de texto “¡Hola Mundo!”
'''

def mensaje():
  print("Hola Mundo")

mensaje()

'''
Ejercicio 2:
Crear un programa que almacene en una variable la cadena de texto 
“¡Hola Mundo!” y luego la muestre por pantalla.
'''

def mensaje():
  texto = "Hola Mundo"
  print(texto)

mensaje()

'''
Ejercicio 3:
3. Crear un programa que pida al usuario su nombre y su edad y luego muestre 
por pantalla los siguientes mensajes en renglones distintos:

> Hola {nombre}
Tu edad es {edad} años
'''

nombre = input("Nombre completo: ")
edad = int(input("Edad: "))

def mensaje():
  print(f"Hola {nombre}.")
  print(f"Tu edad es {edad} años.")
print()

mensaje()

'''
Ejercicio 4:
Crear un programa que pida al usuario su nombre y muestre por 
pantalla cuántas letras tiene.
'''

nombre = str(input("Cómo es tu nombre? "))
def cantidad():
  letras = str(len(nombre))
  print(f"{nombre}, tu nombre tiene {letras} letras.")
print()

cantidad()

'''
Ejercicio 5:
Crear un programa que realice la siguiente operación aritmética 
(3*8/2)2 y muestre por pantalla el resultado.
'''

def operacion (a, b, c, d):
  calculo = (a*b/c)**d
  return calculo

print(round(operacion(3, 8, 2, 2)))

'''
Ejercicio 6:
Crear un programa que lea un entero positivo, n, introducido por el usuario 
y después muestre en pantalla la suma de todos los enteros desde 1 hasta n.
'''

num = int(input("Introduzca un número: "))
def sumatoria():
  suma = 0
  for i in range(1, num +1):
    suma += i
    print(suma)

sumatoria()

'''
Ejercicio 7:
Crear un programa que pida al usuario el monto a invertir y calcular cuánto 
dinero tendrá en su cuenta al cabo de 6 meses si el interés mensual es 
de 5%. Mostrar el resultado por pantalla.
'''

monto = float(input("Introduzca el monto a invertir: $"))
def calculo():
  interes = 0.05
  meses = 6
  total = str(round((monto * interes * meses) + monto))
  print(total)

calculo()

'''
Ejercicio 8:
Crear un programa que pida al usuario su edad y muestre por pantalla
si es mayor de edad o no
'''

edad = int(input("Ingrese su edad: "))
print()
def age():
  if edad < 18:
    print("Sos menor de edad.")
  else:
    print("Sos mayor de edad.")

age()

'''
Ejercicio 9:
Crear un programa que almacene la cadena de caracteres contraseña en 
una variable, pregunte al usuario por la contraseña e imprima por pantalla 
si la contraseña introducida por el usuario coincide con la guardada en 
la variable sin tener en cuenta mayúsculas y minúsculas.
'''

contraseña = "Contraseña1234"
contraseña1 = str(input("Ingrese una contraseña: "))

def password():
  if contraseña == contraseña1:
    print("La contraseña coincide")
  else:
    print("La contraseña no coincide")
    
print()
password()

'''
Ejercicio 10:
Crear un programa que pida al usuario dos números y muestre por pantalla 
el cociente de la división entre ellos siempre que el segundo
número sea distinto de 0.
'''

def numbers():
  numero_1 = int(input("Ingrese su primer número: "))
  numero_2 = int(input("Ingrese su segundo número mayor que cero: "))
  print()
  print(numero_1 / numero_2)
  print(round(numero_1 / numero_2))

numbers()

'''
Ejercicio 11:
Crear un programa que pida al usuario un número entero y 
muestre por pantalla si es par o impar.
'''

def pares_impares():
  numero = int(input("Ingrese un número entero: "))
  if numero %2 == 0:
    print("Tu número es par")
  else:
    print("Su número es impar")

pares_impares()

'''
Ejercicio 12:
Crear un programa que pida al usuario una palabra y
la muestre por pantalla 10 veces.
'''

def words():
  palabra = input("Ingrese una palabra: ")
  print((palabra + " ") * 10)

words()

'''
Ejercicio 13:
Crear una lista con 6 elementos, luego recorrerla e 
imprimir elemento a elemento en renglones distintos.
'''

def list():
  lista = [123, "pancho", "hamburguesa", False, (34), (1, 5)]
  for i in lista:
    print(i)

list()

'''
Ejercicio 14:
Crear un programa que recorra un diccionario previamente creado y 
muestre por pantalla:
> clave → valor
'''

def dict():
  diccionario_gatos = {
        "Nombre": "Sköll",
        "Raza": "No tiene",
        "Edad": "7",
        "Pelaje": "Corto",
        "Color": "Blanco y negro" 
        }
        
  for key, value in diccionario_gatos.items():
    print(f"{key} ---> {value}")

dict()

'''
Ejercicio 15:
Crear un programa que imprima por pantalla todo lo que el usuario ingresa 
hasta que ingresa la palabra “salir”.
'''

def program():
  while True:
    palabras = input("Ingrese una palabra: ")
    print(palabras)
    if palabras == "salir":
      break

program()